export const METRIC_HINTS = {
  totalLeads: "All web and offline inquiries this period — the headline measure of whether new demand is growing.",
  webLeads: "Website form fills this period — how well search and ads are turning visits into inquiries.",
  offlineLeads: "Phone, email, referral, trade-show, and social inquiries logged this period — demand that never hits the website.",
  keywordsTop3: "Queries ranking in positions 1–3 right now — the terms most likely to win the click.",
  organicReach: "Google Search impressions this period — how often the company appeared in unpaid results.",
  organicTraffic: "Organic sessions this period — people who arrived from unpaid search.",
  newUsers: "First-time visitors this period — whether search is bringing in new customers.",
  totalKeywords: "Distinct queries the site ranks for today — the size of the organic footprint.",
  searchClicks: "Unpaid search clicks this period — visits Google sent from organic results.",
  searchImpressions: "Times the site showed in Google Search this period — visibility before the click.",
  searchCtr: "Organic clicks divided by impressions this period — how compelling the listing is when people see it.",
  avgPosition: "Impression-weighted Google ranking across queries — lower is better and means you are closer to the top.",
  googleSpend: "Google Ads spend this period — the budget used to buy search and display demand.",
  googleImpressions: "Times Google Ads were shown this period — paid reach in Search and Display.",
  googleClicks: "Paid Google Ads clicks this period — visits you bought from Google.",
  googleCpc: "Average cost per Google Ads click — whether each paid visit is getting cheaper or more expensive.",
  googleConversions: "Google Ads conversions this period — paid actions that count as leads.",
  googleCostPerConversion: "Google Ads spend divided by conversions — what each paid Google lead is costing.",
  adsCostPerConversion: "Google plus Meta spend per conversion — the blended cost of a paid lead.",
  metaSpend: "Meta Ads spend this period — budget used on Facebook and Instagram.",
  metaImpressions: "Times Meta ads were shown this period — paid social reach.",
  metaClicks: "Meta ad clicks this period — visits and taps you paid for on Facebook and Instagram.",
  metaCpc: "Average cost per Meta click — what each social visit is costing.",
  metaLeads: "Leads attributed to Meta ads this period — paid social demand.",
  metaCtr: "Meta clicks divided by impressions this period — how well the creative earns attention.",
  metaCostPerLead: "Meta spend divided by Meta leads — the cost of each paid social lead.",
  aiTotal: "Sessions from AI chat tools this period — whether answer engines are sending people to the company.",
  chatgpt: "Sessions referred from ChatGPT this period — a signal that the assistant is recommending this company.",
  gemini: "Sessions referred from Gemini this period — Google’s AI sending traffic to the site.",
  perplexity: "Sessions referred from Perplexity this period — citation traffic from that answer engine.",
  claude: "Sessions referred from Claude this period — Anthropic’s assistant sending people to the company.",
  copilot: "Sessions referred from Microsoft Copilot this period — AI search traffic from that assistant.",
  bing: "Sessions referred from Bing this period — Microsoft search traffic, including AI-influenced visits.",
} as const;

export type MetricHintId = keyof typeof METRIC_HINTS;
